### ISSUE TITLE
Want to correct some spelleing error in the website

### ISSUE THREAD

**Issue by Ericchuk** [Diptenusarkar/html.org.in#17]

**Comment by anshul137** [comment]
hey, is it fixed i can help you with this issue.

**Comment by Diptenusarkar** [comment]
@anshul137 No it's not fixed, You Help with that one.

**Comment by anshul137** [comment]
send you the [PR](https://github.com/Diptenusarkar/html.org.in/pull/30)

**Comment by Ericchuk** [comment]
I am working on it
