### ISSUE TITLE
HTML Links document

### ISSUE THREAD

**Issue by jatin00000** [Diptenusarkar/html.org.in#21]
Hi @Diptenusarkar !!, I want to add the documentation for the HTML Links Can you assign me this issue?

**Comment by jatin00000** [comment]
I want to make my First Ever open Source Contribution.

**Comment by jatin00000** [comment]
I had successfully made the pull request. https://github.com/Diptenusarkar/html.org.in/pull/27
Please review  and Merge it.

**Comment by Diptenusarkar** [comment]
You close you pr

**Comment by jatin00000** [comment]
Done!! The upgrade https://github.com/Diptenusarkar/html.org.in/pull/28
