### ISSUE TITLE
Addition of some powerful html tags/attributes 

### ISSUE THREAD

**Issue by Muhammad235** [Diptenusarkar/html.org.in#23]
Disabling of right click using html, to open the front camera on a web page using html and more of this powerful but unused html tags/attribute.

**Comment by Muhammad235** [comment]
Want to make my first pull request ever should I make my folder html_myrealname

**Comment by Muhammad235** [comment]
Please can I get a comment on this

**Comment by Diptenusarkar** [comment]
> Want to make my first pull request ever should I make my folder html_myrealname

No

**Comment by Muhammad235** [comment]
what should I use to save my folder name

**Comment by Muhammad235** [comment]
I have remove my name has you have said, changed the folder name to html_

**Comment by PRO-BROS** [comment]
Hey you can study tags and attributes from [here](https://prhocoding.com/)
