### ISSUE TITLE
Not completely responsive

### ISSUE THREAD

**Issue by navaneethmanoj** [Diptenusarkar/html.org.in#39]
It is not responsive for screen size Mobile L, and devices like Blackberry playbook and Surface Duo. 
![Screenshot (1)](https://user-images.githubusercontent.com/36037989/195663348-62aad2bd-6dc3-4572-b172-4abd1a8d5c11.png)

Can you assign me this issue?

**Comment by Diptenusarkar** [comment]
Best of luck 🤞
