### ISSUE TITLE
Feature: I want to add HTML Vscode extension section in this project

### ISSUE THREAD

**Issue by ShahrozAhmd** [Diptenusarkar/html.org.in#4]
There are a lot of HTML extension which use in vs code and make life easier of developer, I regret that why i don't know about them when I started to code so I want to share it with all, kindly assign this feature to me

**Comment by ShahrozAhmd** [comment]
Hey 👋  @Diptenusarkar  kindly assign this to me, thanks alot

**Comment by Diptenusarkar** [comment]
Hello @ShahrozAhmd,
how exactly you are going to do this? Could you please explain this?

**Comment by ShahrozAhmd** [comment]
I will explain it in article as well as attach extensions working gifs and their link sot install them in vs code

**Comment by ShahrozAhmd** [comment]
Thanks @Diptenusarkar 👍
