### ISSUE TITLE
Adding new feature Prettier and linter

### ISSUE THREAD

**Issue by anshul137** [Diptenusarkar/html.org.in#74]
Hi 
### Adding the code formatter
I would like to add the [prettier](https://prettier.io) in this project which is an automatic source code formatters. It take source code as input and produce properly formatted output. Their goal is to establish a common format for all source code in the project.

### Adding the linter 
Linters help us spot "silly" mistakes that all programmers make, or help us avoid certain code patterns that often lead to bugs. We want to make it easy for ourselves and new developers joining our project to not introduce bugs or bad code.
I will use [ESlint](https://eslint.org/)

And i will Create a simple "one-step" solution for running your formatter and the linter on the entire project from the command line. This could be an `npm script`.
Please assign me thsi issue as well i will work on it.
Thanks

**Comment by Diptenusarkar** [comment]
Why do we need Prettier All Code are already formatted. 
Maybe I missed the point is that possible for you to describe more.
