### ISSUE TITLE
I can fix the card ui of the homepage

### ISSUE THREAD

**Issue by Debshibraj123** [Diptenusarkar/html.org.in#77]
@Diptenusarkar  The paragraph of the cards are overflowing I can fix it. please assign me this topic I can work on this.

**Comment by Diptenusarkar** [comment]
Yes You can

**Comment by Diptenusarkar** [comment]
Hello @Debshibraj123, As you can see your particular home page UI issue was fixed with #83 in this PR. 
You can create your new issue.
