### ISSUE TITLE
bug : homepage cards issue 

### ISSUE THREAD

**Issue by rohitroy-github** [Diptenusarkar/html.org.in#81]
When I opened the site on my laptop, it looked like this >>> 

![image](https://github.com/Diptenusarkar/html.org.in/assets/68563695/177eb56a-1ee6-47c7-817d-2b47296a6d13)

Is it supposed to look like this, or should I have a look into it if you want in accordance with Hacktoberfest !

**Comment by Diptenusarkar** [comment]
Hello @rohitroy-github , As you can see your particular home page UI issue fix with #83 this PR. 
You can create your new issue.
