### ISSUE TITLE
[Alart] : Website is no longer Responsiveness 

### ISSUE THREAD

**Issue by abulgit** [Diptenusarkar/html.org.in#95]
**The responsiveness of UI is broken**
need to Restore the Old Codebase, This happens After the #80 Merge.

**Steps To Reproduce--**

1. Open [Website](https://www.html.org.in/) on Phone Screen
2. Or go to the [Website](https://www.html.org.in/) ->go to inspect tool -->Check Responsiveness 

**Screenshot---**
From Mobile Screen-

![photo_2023-10-06_21-58-15](https://github.com/Diptenusarkar/html.org.in/assets/140191921/0f327063-ca86-4046-a36f-8c3064b7ba9b)

**Comment by Diptenusarkar** [comment]
Can You fix this problem?

**Comment by abulgit** [comment]
Yeah
